import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Toaster } from "sonner";
import ModalProvider from "@/providers/modal-provider";
import NextTopLoader from 'nextjs-toploader';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <EdgeStoreProvider>
      <NextTopLoader
color="#C6A046"

/>

       
        {children}
      
        </EdgeStoreProvider>
        <Toaster position="top-right" richColors />
        <ModalProvider/>
        </body>
    </html>
  );
}
